receivers:
  fluentforward:
    endpoint: 0.0.0.0:24224

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  loadbalancing:
    protocol:
      otlp:
        timeout: 1s
        insecure: true
    resolver:
      static:
        hostnames:
          - otel-collector-1:4317
          - otel-collector-2:4317
          - otel-collector-3:4317

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    logs:
      receivers: [fluentforward]
      processors: [batch]
      exporters: [loadbalancing, logging]
